---
- name: Play that deploys Jenkins after configuring VirtualBox and Vagrant
  hosts:
    - demo
  vars:
    vj_path: /home/{{ ansible_user }}/vagrant-jenkins
  pre_tasks:
    - name: Ensure that the vagrant-jenkins directory exists
      file:
        path: "{{ vj_path }}"
        state: directory

    - name: Drop Vagrantfile onto host machine
      template:
        src: templates/Vagrantfile.j2
        dest: "{{ vj_path }}"

    - name: Ensure that the Ansible provisioning directory exists
      file:
        path: "{{ vj_path }}/ansible"
  roles:
    - install_vbox
    - install_vagrant
    

